name: Test Versioning Workflow

on:
  push:
    branches:
      - initial-implementation

permissions:
  contents: write

jobs:
  deploy-prod1-mock:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mock Deploy Job 1 successful"

  deploy-prod2-mock:
    runs-on: ubuntu-latest
    needs: deploy-prod1-mock
    steps:
      - run: echo "Mock Deploy Job 2 successful"

  version-and-tag:
    runs-on: ubuntu-latest
    needs: deploy-prod2-mock
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Manually Create and Push Tag
        run: |
          MANUAL_TAG_NAME="v-manual-test-${{ github.run_id }}-${{ github.run_attempt }}"

          echo "Commit SHA atual: ${{ github.sha }}"
          echo "Criando tag anotada: ${MANUAL_TAG_NAME}"
          
          git tag -a "${MANUAL_TAG_NAME}" -m "Tag de teste manual criada pelo workflow ${{ github.run_id }}" "${{ github.sha }}"
          
          echo "Enviando (push) a tag: ${MANUAL_TAG_NAME}"
          git push origin "${MANUAL_TAG_NAME}"
          
          echo "Tag ${MANUAL_TAG_NAME} enviada para o repositório."
          echo "Verifique se o seu outro workflow (acionado por 'on: push: tags: ['*']') foi disparado."